### ISSUE TITLE
There is no base_mount information

### ISSUE THREAD

**Issue by junghs1040** [chvmp/chicken_head#1]
There is no base_mount information in champ_arm.urdf
and in mesh file there is no base_mount STL file

so when I launch the demo.launch to simulate the chicken_head in rviz
No transform from [base] to [/odom] error occured and didn't move

**Comment by grassjelly** [comment]
thanks for reporting the issue. Just fixed this https://github.com/chvmp/chicken_head/commit/6258737108555f105a7604914eb9eac94593b7e6 . Thanks!

**Comment by junghs1040** [comment]
thank you!
but I tried to simulate it but it didn't work..
I tried rosrun rqt_tf_tree 
and i saw that base of the arm didn't connected with robot's body
![frames](https://user-images.githubusercontent.com/19335771/111772452-35bc6600-88f0-11eb-873d-863fb278312c.png)

**Comment by grassjelly** [comment]
Mine looks okay after fixing the callback. Silly question, did you pull the most recent updates? Did you rebuild your workspace (cd <your_ws> && catkin_make) ?

**Comment by junghs1040** [comment]
Thank you 
I rebuilded that but it didn't work 
All the arm parts are didn't connected in rviz
![Screenshot from 2021-03-19 20-45-53](https://user-images.githubusercontent.com/19335771/111775496-2f2fed80-88f4-11eb-8907-bc50be4e24da.png)

**Comment by grassjelly** [comment]
Is your joystick connected? Realized z gets uninitialized when the joystick's not detected on runtime. Fixed https://github.com/chvmp/chicken_head/commit/b275f6de03790c7939cb395677e10d479529d539.

**Comment by junghs1040** [comment]
thank you it now connected !!
but it didn't move by keyboard control

**Comment by junghs1040** [comment]
thank you
It works now!!

**Comment by grassjelly** [comment]
Cool! Have fun! :)
